# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.SmallIntegerField(choices=[(0, '未知'), (1, 'http'), (2, 'https'), (3, 'http + https')], default=0, verbose_name='代理类型')),
                ('types', models.SmallIntegerField(choices=[(0, '未知'), (1, '高匿'), (2, '普匿'), (3, '透明')], default=0, verbose_name='匿名程度')),
                ('ip', models.CharField(max_length=16, null=True, verbose_name='ip')),
                ('port', models.CharField(max_length=12, null=True, verbose_name='端口号')),
                ('speed', models.CharField(max_length=12, null=True, verbose_name='响应速度')),
                ('ip_address', models.CharField(max_length=64, null=True, verbose_name='ip地址')),
                ('verify_time', models.DateTimeField(auto_now=True, verbose_name='最后验证时间')),
            ],
            options={
                'db_table': 'proxy_ip',
            },
        ),
    ]
